services:
  order-service:
    build: 
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/order_service_db
      - DB_HOST=database
      - POSTGRES_DB=order_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  database:
    image: postgres:14.1-alpine
    restart: always
    container_name: order-service-database
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_service_db
    ports:
      - 5433:5433
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - SERVICES=sqs, sns, s3
    ports:
      - '4566:4566'
volumes:
  db:
    driver: local