@account_id = 45c01a73-5058-4135-84a7-01b964377ef8


post http://localhost:3001/api/v1/order
X-ACCOUNT-ID : {{account_id}}
content-type : application/json

{
    "providerId" : 1000,
    "comment" : "comment",
    "clientContact" : "1st street 123",
    "deliveryAddress" : "1st street 123",
    "orderItemId" : 1,
    "orderSubItemIds" : [
        {
            "id" : 1,
            "quantity" : 2
        },
        {
            "id" : 2,
            "quantity" : 3
        }
    ]
}