/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.order.controller;

import com.order.model.OrderGetReturnModel;
import com.order.model.OrderPostRequestModel;
import com.order.model.OrderPostReturnModel;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.UUID;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
public interface OrderApi {

  /**
   * POST /api/v1/order create an order
   *
   * @param X_ACCOUNT_ID (required)
   * @param orderPostRequestModel Order to be created (required)
   * @return Created (status code 201) or Conflict! (status code 409) or Not found! (status code
   *     404)
   */
  @RequestMapping(
      method = RequestMethod.POST,
      value = "/api/v1/order",
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<OrderPostReturnModel> createOrder(
      @NotNull @RequestHeader(value = "X-ACCOUNT-ID", required = true) UUID X_ACCOUNT_ID,
      @Valid @RequestBody OrderPostRequestModel orderPostRequestModel)
      throws Exception;

  /**
   * GET /api/v1/order/{order-id} get Order
   *
   * @param X_ACCOUNT_ID (required)
   * @param orderId (required)
   * @return retrieved (status code 200) or Not found! (status code 404)
   */
  @RequestMapping(
      method = RequestMethod.GET,
      value = "/api/v1/order/{order-id}",
      produces = {"application/json"})
  ResponseEntity<OrderGetReturnModel> getOrder(
      @NotNull @RequestHeader(value = "X-ACCOUNT-ID", required = true) UUID X_ACCOUNT_ID,
      @PathVariable("order-id") Long orderId)
      throws Exception;
}
